---
all:
  children:
    # LOCAL
    local:
      hosts:
        local0:
          ansible_connection: local
    # CLUSTER NODES
    allnodes:
      children:
        # MASTER NODES
        masters:
          children:
            # MASTER 1
            # TODO: Generify to allow for X amount of masters
            mainMaster:
              hosts:
                master0:
                  ansible_host: "{{hostnames[0]}}"
                  name: "{{hostnames[0]}}"
                  initial_advertise_peer_url: https://{{hostnames[0]}}:2380
                  listen_peer_url: https://{{hostnames[0]}}:2380
                  listen_client_urls:
                    - https://{{hostnames[0]}}:2379
                    - http://127.0.0.1:2379
                  advertise_client_url: https://{{hostnames[0]}}:2379
            # SECONDARY MASTERS
            secondaryMasters:
              hosts:
                master1:
                  ansible_host: "{{hostnames[1]}}"
                  name: "{{hostnames[1]}}"
                  initial_advertise_peer_url: https://{{hostnames[1]}}:2380
                  listen_peer_url: https://{{hostnames[1]}}:2380
                  listen_client_urls:
                    - https://{{hostnames[1]}}:2379
                    - http://127.0.0.1:2379
                  advertise_client_url: https://{{hostnames[1]}}:2379
                master2:
                  ansible_host: "{{hostnames[2]}}"
                  name: "{{hostnames[2]}}"
                  initial_advertise_peer_url: https://{{hostnames[2]}}:2380
                  listen_peer_url: https://{{hostnames[2]}}:2380
                  listen_client_urls:
                    - https://{{hostnames[2]}}:2379
                    - http://127.0.0.1:2379
                  advertise_client_url: https://{{hostnames[2]}}:2379
          # VARIABLES FOR MASTER NODES
          vars:
            pod_subnet: "100.96.0.0/11"
            apiserver_count: "3"
        # WORKER NODES
        workers:
          hosts:
            worker0:
              ansible_host: 172.26.22.100
              name: worker0
      # VARIABLES FOR ALL NODES
      vars:
        master0_url: "{{hostnames[0]}}"
        master1_url: "{{hostnames[1]}}"
        master2_url: "{{hostnames[2]}}"
        master_api_port: 6443
        ansible_connection: ssh
  # VARIABLES FOR ALL HOSTS
  vars:
    hostnames:
      - 172.26.22.120
      - 172.26.22.121
      - 172.26.22.122
      - 172.26.22.123
      - 172.26.22.124
      - 172.26.22.125
      - 172.26.22.126
      - 172.26.22.127
      - 172.26.22.128
      - 10.96.0.1
      - 127.0.0.1
      - "{{cluster_name}}"
      - "{{cluster_name}}.default"
      - "{{cluster_name}}.default.svc"
      - "{{cluster_name}}.default.svc.cluster"
      - "{{cluster_name}}.default.svc.cluster.local"
    kubernetes_version: 1.12.3
    control_plane_endpoint: "127.0.0.1:32443"
    cluster_name: kubernetes
