global:
  cluster-name: frodo.synthesis.rocks

aws-service-operator:
  operator:
    account: "931486170612"
    cluster: polaris       # Can't contain any weird characters!
    region: eu-west-1

external-dns:
  image:
    name: registry.opensource.zalan.do/teapot/external-dns
    tag: v0.5.4
  logLevel: debug
  rbac:
    create: true

cluster-autoscaler:
  rbac:
    create: true
  cloudProvider: aws
  awsRegion: eu-west-1
  autoscalingGroups:
   - name: nodes.frodo.synthesis.rocks
     minSize: 1
     maxSize: 6

nginx-ingress:
  rbac:
    create: true
  controller:
    publishService:
      enabled: true
    extraArgs:
      enable-ssl-passthrough: true

flux:
  helmOperator:
    create: true
    git:
      chartsPath: "ref4/cluster-repo/charts"
  git:
    url: "git@github.com:davidwebstar34/ExampleFluxRepo.git"
    branch: "master"
    path: "ref4/cluster-repo/"
    user: "polaris"
    email: "davidw4@synthesis.co.za"
    setAuthor: true
    pollInterval: "1m"
  registry:
    pollInterval: "1m"

dex:
  secret:
    tlsName: dex-tls
    caName: dex-ca
  ingress:
     host: dex.frodo.synthesis.rocks
  config:
    issuer: https://dex.frodo.synthesis.rocks
  connectors:
  - type: microsoft
    id: microsoft
    name: Microsoft
    config:
      clientID: 33d82f8b-4db4-4d99-b610-0768ddd246df
      clientSecret: lmwcHDOCUH74+zgbA152:]!
      redirectURI: https://dex.frodo.synthesis.rocks/callback
    #  tenant: organizations
    #
    # Also - edit the application manifest (in MS Apps) and
    # edit to include the valid reply urls:
    # "replyUrls": [
    #    "https://dex.ref4.onlabs.cloud/callback"
    #]
    #
    # Then - need to approve the access using something like this:
    #
    # https://login.microsoftonline.com/94cfdb85-3d23-4849-a066-5cdad965ccd8/adminconsent?client_id=33d82f8b-4db4-4d99-b610-0768ddd246df
  staticClients:
  - id: kubectl-access
    redirectURIs:
    - 'http://127.0.0.1:5555/callback'
    - 'https://login.frodo.synthesis.rocks/callback/frodo.synthesis.rocks'
    name: 'Kubectl Access'
    secret: rkKR4TX1RsK8OvVVufe45KIsuxN4A86B
  enablePasswordDB: true
  staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  - email: "retail@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "retail"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5467"

dex-k8s-authenticator:
  dexK8sAuthenticator:
    port: 5555
    debug: false
    web_path_prefix: /
    clusters:
    - name: frodo.synthesis.rocks
      short_description: "Ref4 Cluster"
      description: "Reference number 4"
      client_secret: rkKR4TX1RsK8OvVVufe45KIsuxN4A86B
      issuer: https://dex.frodo.synthesis.rocks
      k8s_master_uri: https://api.frodo.synthesis.rocks
      client_id: kubectl-access
      redirect_uri: https://login.frodo.synthesis.rocks/callback/frodo.synthesis.rocks
      #
      # Make this particular link public in s3:
      k8s_ca_uri:
        https://s3-eu-west-1.amazonaws.com/kops-mimic/frodo.synthesis.rocks/pki/issued/ca/6661957841380198014448874128.crt
  caCerts:
    enabled: true
    secrets:
    # Get this value by: cat k8/dex/ca/dex-ca-cert.pem | base64 [-w 0]
    - name: ca1
      filename: ca1.crt
      value:
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNxRENDQVpBQ0NRRDBvK0l3S0pmNXlEQU5CZ2txaGtpRzl3MEJBUXNGQURBV01SUXdFZ1lEVlFRRERBdGsKWlhndGEzVmlaUzFqWVRBZUZ3MHhPVEF5TWpVeE5URTRNamxhRncwME5qQTNNVEl4TlRFNE1qbGFNQll4RkRBUwpCZ05WQkFNTUMyUmxlQzFyZFdKbExXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUFybDhaNGZQV0o2LzZaT1MxTFJ4eHpIWThmVnR3RXdVU3lqVXVURzkvT05RWWZCOHdNSkpGSmR2YWhVRnMKQjdubVU4KzYxd1RyYk1tYW5BK2Yxdy9jbjNZL1dlaHdCYWl5U0NERGpmL0pkUlpnVFMwdk5vaEJYNWYvUk5IRQpnVTlhYTIxQzJmdDFVTWpCWFMvMmdhM3ArZUh6WVNSQ0RNYm5seUhsenhNOFZyc0hXaHRINFN5a0RzTWRaY0gzClpWV3psaFBqYXU2cDRrWDgzaVRoNXBwV1ZHMnBwTDFFaTdKYm1ucTJUdEZLYmVubVllbWprKzYyWlN1WmtKSEoKcDlCakp2VVEvVG9STTcwN294Vmc3MzF0T2ZKR0NtSEpPN3NYU2J6ZkhwVm4rWWcrR2tBWTBlbHBMS3djeW1JVApobjg4Zkt2YkFpb2pEZzdwbkZsb2Z2dUVuUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0sxR0tuCmdJY1dsRGlkR3VVcmVXb2ZjdjBqVHd6UENzU09NSVg4amRDbUlCUG5TM2hNVUF0QThZNFA4bVdqVG9wRCtSdHYKbmlWaUk1eVd0RDdRMnJOSjJ5VnZncmFGSkpjSVI5a241N1BSKzZiK3VWclUrblhpcE9Rb3hjUENBb1BZK09kbwp3RFJNbURic3IyU3Q1WlpTT2U3c0NQYmRESXlaS1RXVW5zSlJyVEMwS3h6eUZmc1dDL2ZDYkhJTkVBc09Ic1JFClJZTUdUdmRrTHQ3YkFqa0dSbTVFRmFidC9uUTl3bHhaU1JZL2ZBMTgzZjVJSzRJVndwZVJoZTBLL0lHOVBqNHIKSzR1cDhsd2pUOHZkREUyb00zV0piSmRvWEtXNmFDYjh5R2Q3WitGUGJQbGFxMWVITmlZL0RBcEdQV2tPaG53NQo2MDE4THFKQ016U1hvM2RvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - login.frodo.synthesis.rocks
    tls:
      - hosts:
        - login.frodo.synthesis.rocks
